version: 2.1
jobs:
  Test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name : Kick off new pipeline
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/gh/johntripla/postman-circleCI/pipeline' \
            --header 'Content-Type: application/json' \
            -u "${API_TOKEN}:"
workflows:
  build_test:
    jobs:
      - Test